    include "constants.asm"
    include "autogenerated/text-constants.asm"

; the first time this is compiled, we need a few symbols to be defined 
; to bootstrap the process. Comment the inclusion of trition.sym and Uncomment these 
; constant definition lines:
	include "../triton.sym"
keyboard_line_clicks:       equ keyboard_line_state+1

; global_state_minimap:	equ 0
; random:					equ 0
; StopMusic:		equ 0
; enable_VDP_output:		equ 0
; disable_VDP_output:		equ 0
; set_bitmap_mode_a_color:	equ 0
; update_keyboard_buffers:	equ 0
; fast_FILVRM:			equ 0
; draw_text_from_bank_16:	equ 0
; wait_b_halts:			equ 0
; clearScreenLeftToRight:	equ 0
; set_bitmap_mode:		equ 0
; unpack_compressed:			equ 0
; fast_LDIRVM:			equ 0
; call_from_page1:		equ 0
; play_song:				equ 0
; draw_text_from_bank_slow:	equ 0
; draw_tile_bitmap_mode_by_index:	equ 0
; clearScreen:			equ 0
; set_bitmap_name_table_bank3:	equ 0
; draw_text_from_bank:	equ 0
; play_SFX_with_high_priority:	equ 0
; state_gameover_screen:	equ 0
; state_game_start:		equ 0
; clear_rectangle_bitmap_mode:	equ 0
; draw_text_from_bank_reusing:	equ 0
; clear_text_rendering_buffer:	equ 0
; Div8:					equ 0
; draw_sentence:			equ 0
; draw_tile_bitmap_mode:	equ 0

; decompress_story_song_from_page1:	equ 0
; decompress_mission_song_from_page1:	equ 0
; decompress_weapon_data_from_page1:	equ 0
; decompress_weapons_song_from_page1:	equ 0

; line1_next_ptr: equ 0
; line1_state:    equ 0
; line2_next_ptr: equ 0
; line2_state:    equ 0
; line2_delay:    equ 0
; frame_width:    equ 0
; frame_height:   equ 0
; ui_cursor_area:     equ 0
; ui_cursor_position: equ 0
; ui_selected_weapon: equ 0
; ui_cursor_sprites:  equ 0
; ui_upgrade_scroll_position:  equ 0
; cutscene_gfx_buffer:    equ 0
; pcg_minimap_nw_point:        equ 0
; pcg_minimap_middle_point:    equ 0
; pcg_minimap_se_point:        equ 0

; text_skip:					equ 0
; isComputer50HzOr60Hz:		equ 0
; global_state_boss1_position:	equ 0
; global_state_boss2_position:	equ 0
; global_state_boss3_position:	equ 0
; global_state_credits:		equ 0
; global_state_levels_completed:	equ 0
; global_state_bosses_defeated:	equ 0
; global_state_weapon_configuration:	equ 0
; global_state_weapon_upgrade_level:	equ 0
; global_state_selected_level:	equ 0
; global_state_selected_level_boss:	equ 0
; global_state_selected_level_type:	equ 0
; buffer:						equ 0
; text_buffer:				equ 0
; interrupt_cycle:			equ 0

; ui_sprites_plt:				equ 0
; ui_tiles_plt:				equ 0
; cutscene_gfx_plt:			equ 0
; title_screen_tiles_plt:		equ 0
; title_screen_data_plt:		equ 0
; weapon_configuration_default_ROM:	equ 0
; SFX_ui_move:				equ 0
; SFX_ui_wrong:				equ 0
; SFX_ui_select:				equ 0
; mission_cutscenes_gfx:		equ 0
; weapon_gfx_and_names:		equ 0
; weapon_slot_number:			equ 0
; weapon_price:				equ 0
; weapon_max_buyable_upgrades:	equ 0
; weapon_detailed_descritions:	equ 0

    org NON_GAME_COMPRESSED_CODE_START

    ; entry points:
    jp state_braingames_screen
    jp state_mission_screen_from_game_complete
    jp state_mission_screen_from_game_failed
    jp state_gameover_screen
    jp generate_minimap
    jp enable_nearby_minimap_paths
    jp get_minimap_pointer
    jp state_mission_boss_under_cursor

    include "state-story.asm"
    include "pcg-minimap.asm"
    include "state-title.asm"
    include "state-ending.asm"
    include "state-mission.asm"
    include "gfx-bitmap.asm"
    include "state-weapons.asm"
    include "state-gameover.asm"
    include "state-braingames.asm"
    include "state-password.asm"

COMPRESSED_CODE_END:

    IF COMPRESSED_CODE_END > #F300
        ERROR "COMPRESSED_CODE_END > #F300"
    ENDIF



