/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package music;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.StringTokenizer;
import util.APLib;
import util.Pletter;

/**
 *
 * @author santi
 */
public class TSVMusic {
    public static String noteNames[][] = {{"do","c"}, 
                                          {"do#", "reb","c#","db"},
                                          {"re","d"},
                                          {"re#", "mib","d#","eb"},
                                          {"mi","e"},
                                          {"fa","f"},
                                          {"fa#", "solb","f#","gb"},
                                          {"sol","g"},
                                          {"sol#", "lab","g#","ab"},
                                          {"la","a"},
                                          {"la#", "sib","a#","bb"},
                                          {"si","b"}};
    
    public static void main(String args[]) throws Exception
    {        
        createTritonSongs();
 
        //playTSVMusic("data/music/triton-story.csv", 10);
        //playTSVMusic("data/music/triton-start.csv", 10);
        //playTSVMusic("data/music/triton-mission.csv", 6);
        //playTSVMusic("data/music/triton-weapons.csv", 6);
        //playTSVMusic("data/music/triton-boss.csv", 9);
        //playTSVMusic("data/music/triton-moai.csv", 10);
        //playTSVMusic("data/music/triton-tech.csv", 11);
        //playTSVMusic("data/music/triton-temple.csv", 7);
        //playTSVMusic("data/music/triton-water.csv", 9);
//        playTSVMusic("data/music/triton-ending.csv", 11);
    }
    
    
    
    public static void createTritonSongs() throws Exception
    {
        MSXSong story = loadTSVMusic("data/music/triton-story.csv");
        story.loopBackTime = 0;

        MSXSong mission = loadTSVMusic("data/music/triton-mission.csv");
        mission.loopBackTime = 0;

        MSXSong weapons = loadTSVMusic("data/music/triton-weapons.csv");
        weapons.loopBackTime = 0;
        
        MSXSong boss = loadTSVMusic("data/music/triton-boss.csv");
        boss.loopBackTime = 40;

        MSXSong moai = loadTSVMusic("data/music/triton-moai.csv");
        moai.loopBackTime = 0;

        MSXSong tech = loadTSVMusic("data/music/triton-tech.csv");
        tech.loopBackTime = 0;

        MSXSong temple = loadTSVMusic("data/music/triton-temple.csv");
        temple.loopBackTime = 0;

        MSXSong water = loadTSVMusic("data/music/triton-water.csv");
        water.loopBackTime = 1;

        MSXSong ending = loadTSVMusic("data/music/triton-ending.csv");
        ending.loopBackTime = 0;
        
        List<Integer> notesUsed = new ArrayList<>();
        story.findNotesUsedBySong(0, notesUsed);
        mission.findNotesUsedBySong(0, notesUsed);
        weapons.findNotesUsedBySong(0, notesUsed);
        boss.findNotesUsedBySong(0, notesUsed);
        moai.findNotesUsedBySong(0, notesUsed);
        tech.findNotesUsedBySong(0, notesUsed);
        temple.findNotesUsedBySong(0, notesUsed);
        water.findNotesUsedBySong(0, notesUsed);
        ending.findNotesUsedBySong(0, notesUsed);
        Collections.sort(notesUsed);
        System.out.println("; notes used("+notesUsed.size()+"): " + notesUsed);

        System.out.println("");
        System.out.print("; ");
        for(int idx = 0;idx<notesUsed.size();idx++) {
            System.out.print(notesUsed.get(idx) + " ");
        }
        System.out.println("");
        System.out.print("note_period_table:");
        for(int idx = 0;idx<notesUsed.size();idx++) {
            int note = notesUsed.get(idx);
            int period = MSXNote.PSGNotePeriod(note); 
            if (idx%8 == 0) System.out.print("\n  db ");
            System.out.print((period/256) + "," + (period%256));
            if (idx%8 != 7) System.out.print(",  ");
        }
        System.out.println("\n");
        
        compileAssemblerSong(story, "../triton/src/autogenerated/story-song", notesUsed);
        compileAssemblerSong(mission, "../triton/src/autogenerated/mission-song", notesUsed);
        compileAssemblerSong(weapons, "../triton/src/autogenerated/weapons-song", notesUsed);
        compileAssemblerSong(boss, "../triton/src/autogenerated/boss-song", notesUsed);
        compileAssemblerSong(moai, "../triton/src/autogenerated/moai-song", notesUsed);
        compileAssemblerSong(tech, "../triton/src/autogenerated/tech-song", notesUsed);
        compileAssemblerSong(temple, "../triton/src/autogenerated/temple-song", notesUsed);
        compileAssemblerSong(water, "../triton/src/autogenerated/water-song", notesUsed);
        compileAssemblerSong(ending, "../triton/src/autogenerated/ending-song", notesUsed);
    }
    
    
    public static void compileAssemblerSong(MSXSong song, String fileName, List<Integer> notesUsed) throws Exception
    {
        PrintStream w = new PrintStream(new File(fileName + ".asm"));
        song.convertToAssembler("song", notesUsed, w);
        w.flush();
        w.close();  
        
        nl.grauw.glass.Assembler.main(new String[]{fileName + ".asm", fileName + ".bin"});
        Pletter.intMain(new String[]{fileName + ".bin", fileName + ".plt"});  
        APLib.main(fileName + ".bin", fileName + ".apl", true);
    }
    
    public static MSXSong loadTSVMusic(String fileName) throws Exception
    {
        // Init:
        MSXSong song = new MSXSong();
        
        int ch_instrument[] = {MSXNote.INSTRUMENT_SQUARE_WAVE, 
                               MSXNote.INSTRUMENT_SQUARE_WAVE, 
                               MSXNote.INSTRUMENT_SQUARE_WAVE};
        MSXNote channelNotes[] = {null, null, null};
        
        BufferedReader br = new BufferedReader(new FileReader(fileName));
        while(br.ready()) {
            String line = br.readLine();
            String channels[] = line.split("\t");
            for(int channel = 0;channel<channels.length;channel++) {
                String commands[] = channels[channel].split(",");
                for(String command:commands) {
                    command = command.strip();
                    if (command.length() == 0) continue;
                    command = command.toLowerCase();
                    StringTokenizer tokenizer = new StringTokenizer(command, "()");
                    String commandName = tokenizer.nextToken();
                    switch(commandName) {
                        case "-":
                            {
                                MSXNote note = new MSXNote(0);
                                song.channels[channel].add(note);
                                channelNotes[channel] = note;                            
                            }
                            break;
                        case "squarewave":
                            ch_instrument[channel] = MSXNote.INSTRUMENT_SQUARE_WAVE;
                            break;
                        case "piano":
                            ch_instrument[channel] = MSXNote.INSTRUMENT_PIANO;
                            break;
                        case "pianosoft":
                            ch_instrument[channel] = MSXNote.INSTRUMENT_PIANO_SOFT;
                            break;
                        case "wind":
                            ch_instrument[channel] = MSXNote.INSTRUMENT_WIND;
                            break;
                        case "pianostaccato":
                            ch_instrument[channel] = MSXNote.INSTRUMENT_PIANO_STACCATO;
                            break;
                        case "windfading":
                            ch_instrument[channel] = MSXNote.INSTRUMENT_WIND_FADING;
                            break;
                        case "pad":
                            ch_instrument[channel] = MSXNote.INSTRUMENT_PAD;
                            break;
                        case "fade":
                            ch_instrument[channel] = MSXNote.INSTRUMENT_FADE;
                            break;
                        case "shortwind":
                            ch_instrument[channel] = MSXNote.INSTRUMENT_SHORTWIND;
                            break;
                        case "vibrating":
                            ch_instrument[channel] = MSXNote.INSTRUMENT_PIANO_FREQUENCY_VIBRATION;
                            break;
                        case "repeat":
                            {
                                int parameter = Integer.parseInt(tokenizer.nextToken());
                                MSXNote note = new MSXNote(MSXNote.START_REPEAT, parameter);
                                song.channels[channel].add(note);
                                channelNotes[channel] = note;                            
                            }
                            break;
                        case "endrepeat":
                            {
                                MSXNote note = new MSXNote(MSXNote.END_REPEAT, 0);
                                song.channels[channel].add(note);
                                channelNotes[channel] = note;                            
                            }
                            break;
                        case "sfx":
                            {
                                String sfx = tokenizer.nextToken();
                                MSXNote note = new MSXNote(sfx,0);
                                song.channels[channel].add(note);
                                channelNotes[channel] = note;                            
                            }
                            break;
                        default:
                            // it's a note!
                            String noteStr = command.substring(0, command.length()-1);
                            String octaveStr = command.substring(command.length()-1);
                            int found = -1;
                            for(int idx = 0; idx<noteNames.length; idx++) {
                                String noteGroup[] = noteNames[idx];
                                for(String noteName:noteGroup) {
                                    if (noteStr.equals(noteName)) {
                                        found = idx;
                                        break;
                                    }
                                }
                                if (found != -1) break;
                            }
                            if (found != -1) {
                                int octave = Integer.parseInt(octaveStr);
                                MSXNote note = new MSXNote(octave, found, 15, 0, ch_instrument[channel]);
                                song.channels[channel].add(note);
                                channelNotes[channel] = note;
                            } else {
                                throw new Exception("unrecognized command: " + command);
                            }
                            break;
                    }
                }
            }

            // advance time:
            for(int i = 0;i<3;i++) {
                MSXNote note = channelNotes[i];
                if (note == null) {
                    note = new MSXNote(0);
                    song.channels[i].add(note);
                    channelNotes[i] = note;
                }
                if (note.absoluteNote >= -2) {
                    // if it's a note:
                    note.duration++;
                }
            }
        }

        return song;
    }
    
    public static void playTSVMusic(MSXSong song, int tempo) throws Exception
    {

        List<Integer> buffer = MSXSongWavGenerator.generateBuffer(tempo, song);
        MSXSongWavGenerator.playBuffer(buffer);        
    }
    
    public static void playTSVMusic(String fileName, int tempo) throws Exception
    {
        playTSVMusic(loadTSVMusic(fileName), tempo);
    }    
}
